version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "mefaldemisov/devops_lab_2:latest"
    container_name: devops_lab2_app
    ports:
      - "5000:5000"
