version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "mefaldemisov/devops_course:laaatest"
    container_name: devops_course
    ports:
      - "5000:5000"
    volumes:
      - "./data:/app/data"
