apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
    app: app-python
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: Opaque
data:
  my_secret: '{{ .Values.secret | b64enc }}'
