apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app-python.fullname" . }}
  labels:
    {{- include "app-python.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Chart.Name }}
  podManagementPolicy: {{ .Values.statefulSet.podManagementPolicy }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-python.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-python.selectorLabels" . | nindent 8 }}
    spec:
#      serviceAccountName: {{ include "app-python.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: MY_SECRET
            valueFrom:
              secretKeyRef:
                name: credentials
                key: my_secret
          volumeMounts:
            - name: counter
              mountPath: {{ .Values.image.mountDir }}
  volumeClaimTemplates:
    - metadata:
        name: counter
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 128Mi
